export const Colors = {
  RED_COLOR: 'red',
  WHITE_COLOR: 'white',
  HEADER_LOGO_BG_COLOR: '#F0F0F0',
  HEADER_BORDER_COLOR: '#EAECF0',
  HEADER_TITLE_COLOR: '#101828',
  HEADER_EMAIL_COLOR: '#667085',
};
